# Generated by Django 3.2.16 on 2023-02-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Updated',
            new_name='updated',
        ),
    ]
